dist: trusty
language: node_js
node_js:
- '6'

install:
- npm install

script:
- npm test

before_deploy:
- npm run clean
- npm run build:lib

deploy:
  provider: npm
  email: david.recuencogadea@gmail.com
  api_key: "$NPM_TOKEN"
  on:
    branch: develop
  skip_cleanup: true

after_deploy:
- ./publish.sh

