dist: trusty
language: node_js
node_js:
- '6'

install:
- npm install

script:
- .travis/build-integration.sh

before_deploy:
- .travis/build-production.sh

deploy:
  provider: npm
  email: david.recuencogadea@gmail.com
  api_key: "$NPM_TOKEN"
  on:
    branch: develop
  skip_cleanup: true

after_deploy:
- .travis/publish.sh
